### ISSUE TITLE
The program detects all my lines has 'invalid'

### ISSUE THREAD

**Issue by joaoofreitas** [GuardatiSimone/messaging-chat-parser#1]
#### Hello, I've found your project on Reddit, and I'm currently testing this repository.

Well, I tried do preprocess my data, but unfortunally I'm getting this error. Any ideas?

__Command used:__ 
 ` python ./src/whatsapp_parser.py --session_token "<|endoftext|>" --delta_h_threshold 4 --us --user_name johnny`

__Logs:__
` [whatsapp_parser.py][INFO]: WA_STOP_WORDS:['https', '<Media omessi>', '<Media omitted>', 'www'] `

`[whatsapp_parser.py][INFO]: Found 1 txt files in ./data/chat_raw/whatsapp/ folder ['./data/chat_raw/whatsapp/_chat.txt']`

` [whatsapp_parser.py][INFO]: Found 33322 invalid lines in ./data/chat_raw/whatsapp/_chat.txt`

`[whatsapp_parser.py][INFO]: Saving ./data/chat_parsed/wa-chats.txt`

**Comment by pistocop** [comment]
Hi @joaoofreitas, 

### Problem

I think the problem is generated by the parser at [this line](https://github.com/GuardatiSimone/messaging-chat-parser/blob/5050bd5b23d026bc2b52ce240dd6bb16ebf37e42/src/whatsapp_parser.py#L25):
`line_elements = parse.parse("{date}, {time} - {actor}: {text}", line)`

The returned value `line_elements` in your case I think is `None` because the parser can't properly elaborate the line. 

I show one example of my WhatsApp data to show you how my data looks like:

```
12/12/19, 02:09 - My Friend1: bla bla bla bla
12/12/19, 08:40 - Simmy: bla bla bla bla
```


### Datetime parser

I also see you are using the `--us` argument, that is incorrect (in my test the program don't run because can't parse well the arguments), the **old** way to use American format was `--time_format usa`. 

I have recently updated the time format parsing to manage more property the different time format from different countries. You can check the new argument of both parser directly from the README. 

## Possible solution

I think in your case the proper way to parse the chats are:
`python ./src/whatsapp_parser.py --session_token "<|endoftext|>" --delta_h_threshold 4 --user_name johnny --time_format "%d/%m/%y, %H:%M"`

and:
`python ./src/telegram_parser.py --session_token "<|endoftext|>" --time_format "%Y-%m-%dT%H:%M:%S"`

Let me know if this solution work for you.

Regards,
Simone
